# Generated by Django 3.2.25 on 2024-08-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=1000)),
                ('school_bin', models.CharField(max_length=1000)),
                ('sum', models.CharField(max_length=1000)),
                ('txn_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_identifier', models.CharField(max_length=1000)),
                ('school_bin', models.CharField(max_length=1000)),
            ],
        ),
    ]
