# Generated by Django 3.2.25 on 2024-08-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_school_ms_sql_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='ms_sql_transactions_table',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
