# Generated by Django 3.2.25 on 2024-08-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_school_ms_sql_transactions_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='clazz_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
